on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "15 12 * * *"
  workflow_dispatch:
    branches: [main, master]


name: download-sigbm

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Atualizar certificados CA
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Fetch latest data
        run: |-
          curl -k -X POST -d "" https://app.anm.gov.br/SIGBM/Publico/ClassificacaoNacionalDaBarragem/ExportarExcel --output data-raw/sigbm_download_`date +"%Y-%m-%d"`.xlsx

      - name: commit results
        run: |
          git config --local user.email "milz.bea@gmail.com"
          git config --local user.name "Beatriz Milz"
          git add .
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
